
package views.Device;

import Exceptions.NullSelectionException;
import controllers.App;
import controllers.DeviceController;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Device;

/**
 *
 * @author petrix
 */
public class DeviceListView extends views.View {

    private DeviceController deviceController;
    private DefaultTableModel dtmDevices;
    
    private final String[] columnNames = {
        "Id", "Nome"
    };
    
    private void createTableModel() {
        this.dtmDevices = (DefaultTableModel) this.tbDeviceList.getModel();
        this.dtmDevices.setColumnIdentifiers(columnNames);
        this.dtmDevices.setRowCount(0);
    }

    public DeviceListView() {
        initComponents();
        ajustScreenCenter();
        deviceController = new DeviceController();
        this.createTableModel();
        this.ListDevices();
    }
    
    public void ListDevices() {
        this.dtmDevices.setNumRows(0);
        for (Device dev : deviceController.getFilteredDevices()) {
            Object[] listData = {dev.getId(), dev.getName()};
            dtmDevices.addRow(listData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDevice = new javax.swing.JLabel();
        btCreateDevice = new javax.swing.JButton();
        btFilterDevice = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDeviceList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbDevice.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbDevice.setText("Dispositivos");

        btCreateDevice.setText("Cadastrar");
        btCreateDevice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateDeviceActionPerformed(evt);
            }
        });

        btFilterDevice.setText("Pesquisar");
        btFilterDevice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFilterDeviceActionPerformed(evt);
            }
        });

        tbDeviceList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tbDeviceList);
        if (tbDeviceList.getColumnModel().getColumnCount() > 0) {
            tbDeviceList.getColumnModel().getColumn(0).setPreferredWidth(200);
            tbDeviceList.getColumnModel().getColumn(0).setMaxWidth(200);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCreateDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btFilterDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))))
                    .addComponent(lbDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCreateDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFilterDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCreateDeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateDeviceActionPerformed
        App.openDeviceCreateView();
    }//GEN-LAST:event_btCreateDeviceActionPerformed

    private void btFilterDeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFilterDeviceActionPerformed
        this.ListDevices();
    }//GEN-LAST:event_btFilterDeviceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeviceListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeviceListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeviceListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeviceListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeviceListView().setVisible(true);
            }
        });
    }

    @Override
    public void setTitleScreen() {
        setTitle("Consulta de Dispositivos");
    }

    public int validateSelection(int selectedRow) throws NullSelectionException {
        if (selectedRow == -1) {
            throw new NullSelectionException("Dispositivo");
        }
        return (Integer) this.dtmDevices.getValueAt(this.tbDeviceList.getSelectedRow(), 0);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCreateDevice;
    private javax.swing.JButton btFilterDevice;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDevice;
    private javax.swing.JTable tbDeviceList;
    // End of variables declaration//GEN-END:variables
}
