package views.Customer;

import Exceptions.EmptyFieldException;
import daos.CustomerDAO;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import models.Customer;

/**
 *
 * @author max
 */
public class CustomerFormView extends views.View {
    
    public CustomerFormView(){
        initComponents();
    }
    
    public void addCreateCustomerAction(ActionListener action){
        btCreateCustomer.addActionListener(action);
    }
    
    public String getName(){
        return tfName.getText();
    }
    
    public String getCPF(){
        return tfCPF.getText();
    }
    
    public String getaddress(){
        return tfBirthDate.getText();
    }
    
    public String getBirthDAte(){
        return tfBirthDate.getText();
    }
    
    public void showMessage(String msg){
        JOptionPane.showMessageDialog(null, msg);
    }
    
    public void clearFields() {
        tfName.setText("");
        tfCPF.setText("");
        tfaddress.setText("");
        tfBirthDate.setText("");
    }

//    private Customer customer;
//
//    public CustomerFormView(Customer customer) {
//        initComponents();
//        ajustScreenCenter();
//        if (customer != null) {
//            this.customer = customer;
//            this.setCustomerInfo(customer);
//        }
//    }
//
//    public void setCustomerInfo(Customer customer) {
//        tfName.setText(customer.getName());
//        tfCPF.setText(customer.getCPF());
//        tfaddress.setText(customer.getaddress());
//        tfBirthDate.setText(customer.getBirthDate());
//    }
//
//    public Customer getCustomerInfo() throws EmptyFieldException {
//        String name = tfName.getText();
//        String CPF = tfCPF.getText();
//        String address = tfaddress.getText();
//        String birthDate = tfBirthDate.getText();
//        return new Customer(name, CPF, address, birthDate);
//
//    }
//
//    public void createCustomer() throws EmptyFieldException {
//        try {
//            CustomerDAO customerDAO = new CustomerDAO();
//            customerDAO.createCustomer(this.getCustomerInfo());
//            JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso.");
//        } catch (EmptyFieldException emptyFieldException) {
//            JOptionPane.showMessageDialog(null, emptyFieldException.getMessage());
//        }
//
//    }
//
//    public void updateCustomer() {
//        this.customer.setName(tfName.getText());
//        this.customer.setCPF(tfCPF.getText());
//        this.customer.setaddress(tfaddress.getText());
//        this.customer.setBirthDate(tfBirthDate.getText());
//        JOptionPane.showMessageDialog(null, "Cliente alterado com sucesso.");
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfName = new javax.swing.JTextField();
        tfaddress = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btCreateCustomer = new javax.swing.JButton();
        tfCPF = new javax.swing.JFormattedTextField();
        tfBirthDate = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tfName.setName("tfName"); // NOI18N

        tfaddress.setName("tfaddress"); // NOI18N

        jLabel1.setText("Nome");

        jLabel2.setText("CPF");

        jLabel3.setText("Data de Nascimento");
        jLabel3.setName("tfBirthDate"); // NOI18N

        jLabel4.setText("Endereço");

        btCreateCustomer.setText("Cadastrar");
        btCreateCustomer.setName("btCreateCustomer"); // NOI18N

        try {
            tfCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tfBirthDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btCreateCustomer)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfName)
                    .addComponent(tfaddress, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCPF)
                    .addComponent(tfBirthDate)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(tfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(tfBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(tfaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCreateCustomer)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        tfaddress.getAccessibleContext().setAccessibleName("tfEndereco");
        tfaddress.getAccessibleContext().setAccessibleDescription("tfEndereco");
        jLabel3.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCreateCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tfaddress;
    private javax.swing.JFormattedTextField tfBirthDate;
    private javax.swing.JFormattedTextField tfCPF;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setTitleScreen() {
        setTitle("Manutenção de Clientes");
    }
}
